Improving costs page exhibition
globocom/database-as-a-service pull request #747
Opened 2022-08-01 19:55 UTC by Erkmann

Resultado:
![screencapture-0-0-0-0-8000-admin-logical-database-1-cost-2022-08-01-16_48_46](https://user-images.githubusercontent.com/36168066/182233701-66b9d2d9-7ae7-40c4-b2c4-292709e5977a.png)

2022-08-01 20:26 UTC, Erkmann commented
Nova versão com campos solicitados
![screencapture-0-0-0-0-8000-admin-logical-database-1-cost-2022-08-01-17_25_21](https://user-images.githubusercontent.com/36168066/182240966-1c0a47e3-cc52-4645-9dd6-c9fd8d4c8ebf.png)

2022-08-02 00:03 UTC, ricardosdias requested changes
Can you change the text in Portuguese to English?

2022-08-02 12:49 UTC, Erkmann commented
Nova versão em inglês
![screencapture-0-0-0-0-8000-admin-logical-database-1-cost-2022-08-02-09_47_03](https://user-images.githubusercontent.com/36168066/182378475-13454bca-18c1-44ad-8e31-2d825884926e.png)

2022-08-03 11:11 UTC, ricardosdias approved these changes

2022-08-03 12:33 UTC, merged