Feature: Added logic to return an error if the database already exists
globocom/database-as-a-service pull request #814
Opened 2023-02-07 00:33 UTC by Iagohtavares

If a database already exists and/or it is in quarantine, it will return a message explaining to the user to look for the dbaas team. If the database does not exist, the flow remains the same.

2023-02-10 18:21 UTC, nimbfire requested changes
tudo o que o mateus colocou, basicamente :)

2023-02-13 15:07 UTC, nimbfire commented
ó, iago, seu pr ta pra master, tem que ser pra dev

2023-02-13 17:00 UTC, Iagohtavares commented on dbaas/notification/tasks.py
> +        database = get_object_or_404(Database, name=name)
Done!

2023-02-13 17:01 UTC, Iagohtavares commented on dbaas/notification/tasks.py
> +                'Database already exists, but there is in quarantine\n'
Done!

2023-02-13 17:01 UTC, Iagohtavares commented on dbaas/notification/tasks.py
> +                'If you would like know more informations about it, contact DBaaS team in Slack.'
Done!

2023-02-13 17:09 UTC, Erkmann requested changes

2023-02-13 17:09 UTC, Erkmann commented on dbaas/notification/tasks.py
> +    database = Database.objects.filter(name=name)
Utilizar o `Database.objects.filter(name=name).first()`
Na validação seguinte, pode alterar simplismente para `if database:`.

No resto do código quando referenciar a db q veio na consulta, podes usar entao somente `database` (n precisa o [0])!

2023-02-13 17:23 UTC, Iagohtavares commented on dbaas/notification/tasks.py
> +    database = Database.objects.filter(name=name)
Você não está com frio, pois está coberto de razão. 
Alterações feitas!

2023-02-13 17:32 UTC, Erkmann approved these changes

2023-02-15 11:55 UTC, merged