Remove databasereport and sofiadashboard
globocom/database-as-a-service pull request #856
Opened 2023-04-11 21:15 UTC by danylagacione

Removido dashboard Sofia para todos os usuários.
Removida a permissão e a visualização do DatabaseReport. Apenas quem tem a role_dba poderá  ter acesso a funcionalidade.

2023-04-11 21:21 UTC, Iagohtavares approved these changes

2023-04-12 12:36 UTC, nimbfire requested changes

2023-04-12 12:36 UTC, nimbfire commented on dbaas/dbaas/templates/adminplus/index.html
> +                        {% if is_dba or name == 'Plan details' %}
mudar a logica pra editar a custom_list quando ela eh gerada

2023-04-12 12:36 UTC, nimbfire commented on dbaas/dbaas/views.py
> +            'is_dba': is_dba}
n entendi pq esta aqui o is_dba

2023-04-12 12:36 UTC, nimbfire commented on dbaas/dbaas_services/analyzing/views.py
> +        if self.has_perm(request):
o has_perm tem que retornar true/false OU uma renderização, n os dois :p

2023-05-05 14:10 UTC, nimbfire reviewed
Atualizar para o register_view usar o parametro visitble para mostrar ou não a lista

admin.site.register_view('/dashboard/sofia_dashboard/',
                         name='Sofia Dashboard',
                         view=sofia_dashboard)

![image](https://user-images.githubusercontent.com/3688379/236481393-0da6d2e5-964e-4e91-a3fb-800da6f429f0.png)

2023-05-05 14:10 UTC, nimbfire commented
biblioteca usada para procurar referencias
https://github.com/jsocol/django-adminplus

2023-05-30 18:55 UTC, closed without merging